/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selektorgalaktyk;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Quchi
 */
public class OknoListyGalaktyk extends JFrame implements ActionListener{
    int galaktyka = 0;
    Wyświetlacz Wyświetlacz;
    Wyświetlacz Miniatura;
    ArrayList<Galaktyka> ListaGalaktyk;
    /**
     * Creates new form OknoListyGalaktyk
     */
    public OknoListyGalaktyk(ArrayList<Galaktyka> ListaGalaktyk) {
        
        this.ListaGalaktyk = ListaGalaktyk;
        Wyświetlacz = new Wyświetlacz(ZmieńRozmiarObrazu(ListaGalaktyk.get(0).getObraz(),700, 422));
        ustawMiniaturęInicjacja(ListaGalaktyk.get(0).ObrazGalaktyki);
        initComponents();
        ustawDane(ListaGalaktyk.get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelWyświetlacz = Wyświetlacz;
        ButtonPoprzedni = new javax.swing.JButton();
        ButtonNastępny = new javax.swing.JButton();
        LabelPrzeglądanaGalaktyka = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PanelMiniatura = Miniatura;
        jLabel2 = new javax.swing.JLabel();
        LabelŹródło = new javax.swing.JLabel();
        LabelWidok = new javax.swing.JLabel();
        LabelTypGalaktyki = new javax.swing.JLabel();
        LabelPikseleJasne = new javax.swing.JLabel();
        LabelLiczbaJasnychPunktow = new javax.swing.JLabel();
        LabelPikseleJasneWartość = new javax.swing.JLabel();
        LabelPikseleBiałe = new javax.swing.JLabel();
        LabelPikseleBiałeWartość = new javax.swing.JLabel();
        LabelLiczbaJasnychPunktowWartość = new javax.swing.JLabel();
        LabelLiczbaWykrytychJąderGalaktyki = new javax.swing.JLabel();
        LabelLiczbaWykrytychJąderGalaktykiWartość = new javax.swing.JLabel();
        LabelŹródłoWartość = new javax.swing.JLabel();
        LabelWidokWartość = new javax.swing.JLabel();
        LabelTypGalaktykiWartość = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout PanelWyświetlaczLayout = new javax.swing.GroupLayout(PanelWyświetlacz);
        PanelWyświetlacz.setLayout(PanelWyświetlaczLayout);
        PanelWyświetlaczLayout.setHorizontalGroup(
            PanelWyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        PanelWyświetlaczLayout.setVerticalGroup(
            PanelWyświetlaczLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        ButtonPoprzedni.setText("Poprzedni");
        ButtonPoprzedni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPoprzedniMouseClicked(evt);
            }
        });

        ButtonNastępny.setText("Następny");
        ButtonNastępny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNastępnyMouseClicked(evt);
            }
        });

        LabelPrzeglądanaGalaktyka.setText("Dana Wykryta galaktyka: "+String.valueOf(galaktyka+1)+" na: "+(ListaGalaktyk.size())+" ");

        javax.swing.GroupLayout PanelMiniaturaLayout = new javax.swing.GroupLayout(PanelMiniatura);
        PanelMiniatura.setLayout(PanelMiniaturaLayout);
        PanelMiniaturaLayout.setHorizontalGroup(
            PanelMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PanelMiniaturaLayout.setVerticalGroup(
            PanelMiniaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jLabel2.setText("Miniatura Danej Galaktyki");

        LabelŹródło.setText("Źródło z którego wykryto galaktykę: ");

        LabelWidok.setText("Widok na galaktykę:");

        LabelTypGalaktyki.setText("Typ galaktyki:  ");

        LabelPikseleJasne.setText("Piksele jasne:");

        LabelLiczbaJasnychPunktow.setText("Liczba jasnych punktów:");

        LabelPikseleJasneWartość.setText("0");

        LabelPikseleBiałe.setText("Piksele białe:");

        LabelPikseleBiałeWartość.setText("Piksele białe:");

        LabelLiczbaJasnychPunktowWartość.setText("1");

        LabelLiczbaWykrytychJąderGalaktyki.setText("Liczba wykrytych jąder galaktyki: ");

        LabelLiczbaWykrytychJąderGalaktykiWartość.setText("0");

        LabelŹródłoWartość.setText("jLabel3");

        LabelWidokWartość.setText("jLabel3");

        LabelTypGalaktykiWartość.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelWyświetlacz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelŹródło)
                                    .addComponent(LabelWidok)
                                    .addComponent(LabelTypGalaktyki)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPikseleJasne)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LabelPikseleJasneWartość))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelLiczbaJasnychPunktow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LabelLiczbaJasnychPunktowWartość, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPikseleBiałe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LabelPikseleBiałeWartość))
                                    .addComponent(LabelTypGalaktykiWartość)
                                    .addComponent(LabelWidokWartość)
                                    .addComponent(LabelŹródłoWartość)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelLiczbaWykrytychJąderGalaktyki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LabelLiczbaWykrytychJąderGalaktykiWartość, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonPoprzedni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonNastępny)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPrzeglądanaGalaktyka)))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(PanelMiniatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelWyświetlacz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPoprzedni)
                            .addComponent(ButtonNastępny)
                            .addComponent(LabelPrzeglądanaGalaktyka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelŹródło)
                            .addComponent(LabelŹródłoWartość))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelWidok)
                            .addComponent(LabelWidokWartość))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTypGalaktyki)
                            .addComponent(LabelTypGalaktykiWartość))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPikseleJasne)
                            .addComponent(LabelPikseleJasneWartość)
                            .addComponent(LabelPikseleBiałe)
                            .addComponent(LabelPikseleBiałeWartość))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelLiczbaJasnychPunktow)
                            .addComponent(LabelLiczbaJasnychPunktowWartość)
                            .addComponent(LabelLiczbaWykrytychJąderGalaktyki)
                            .addComponent(LabelLiczbaWykrytychJąderGalaktykiWartość))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMiniatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPoprzedniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPoprzedniMouseClicked
        galaktyka--;
        if(galaktyka<0){
            galaktyka = 0;
        }
        Wyświetlacz.UstawNowyObraz(ZmieńRozmiarObrazu(ListaGalaktyk.get(galaktyka).getObraz(),700, 422));
        ustawMiniaturę(ListaGalaktyk.get(galaktyka).getObraz());
        ustawDane(ListaGalaktyk.get(galaktyka));
        Odswierzenie();
        LabelPrzeglądanaGalaktyka.setText("Dana Wykryta galaktyka: "+String.valueOf(galaktyka+1)+" na: "+(ListaGalaktyk.size())+" ");
    }//GEN-LAST:event_ButtonPoprzedniMouseClicked

    
    
    private void ButtonNastępnyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNastępnyMouseClicked
       galaktyka++; // TODO add your handling code here:
       if(galaktyka>=ListaGalaktyk.size()-1){
            galaktyka = ListaGalaktyk.size()-1;
        }
       Wyświetlacz.UstawNowyObraz(ZmieńRozmiarObrazu(ListaGalaktyk.get(galaktyka).getObraz(),700, 422));
       ustawMiniaturę(ListaGalaktyk.get(galaktyka).getObraz());
       ustawDane(ListaGalaktyk.get(galaktyka));
       Odswierzenie();
       LabelPrzeglądanaGalaktyka.setText("Dana Wykryta galaktyka: "+String.valueOf(galaktyka+1)+" na: "+(ListaGalaktyk.size())+" ");
    }//GEN-LAST:event_ButtonNastępnyMouseClicked
    
    
    public void ustawDane(Galaktyka Galaktyka){
        LabelŹródłoWartość.setText(Galaktyka.getŹródło());
        LabelLiczbaJasnychPunktowWartość.setText(String.valueOf(Galaktyka.getLiczbaJasnychPunktów()));
        LabelLiczbaWykrytychJąderGalaktykiWartość.setText(String.valueOf(Galaktyka.getLiczbaJąderGalaktyki()));
        LabelPikseleBiałeWartość.setText(String.format("%.2f", (float)Galaktyka.getPikseleBiałe())+"%");
        LabelPikseleJasneWartość.setText(String.format("%.2f", (float)Galaktyka.getPikseleJasne())+"%");
        LabelTypGalaktykiWartość.setText(String.valueOf(Galaktyka.getTypGalaktyki()));
        LabelWidokWartość.setText(String.valueOf(Galaktyka.getWidokNaGalaktyke()).replace('_', ' '));
    }
    
    public void ustawMiniaturę(BufferedImage img){
        if(img.getWidth()<=200&&img.getHeight()<=200){
            Miniatura.UstawNowyObraz(img);
        }
        
        else if(img.getWidth()>img.getHeight())
                {
            int NowyY = img.getHeight()*200/img.getWidth();
            Miniatura.UstawNowyObraz(ZmieńRozmiarObrazu(img,200,NowyY));
        }
        
        else if(img.getHeight()>img.getWidth())
                {
            int NowyX = img.getWidth()*200/img.getHeight();
            Miniatura.UstawNowyObraz(ZmieńRozmiarObrazu(img,NowyX,200));
        }
         
    }
    public void ustawMiniaturęInicjacja(BufferedImage img){
        if(img.getWidth()<=200&&img.getHeight()<=200){
            Miniatura = new Wyświetlacz(img);
        }
        else if(img.getWidth()>img.getHeight())
                {
            int NowyY = img.getHeight()*200/img.getWidth();
            Miniatura= new Wyświetlacz(ZmieńRozmiarObrazu(img,200,NowyY));
        }
        
        else if(img.getHeight()>img.getWidth())
                {
            int NowyX = img.getWidth()*200/img.getHeight();
            Miniatura = new Wyświetlacz(ZmieńRozmiarObrazu(img,NowyX,200));
        }
         
    }
    public static BufferedImage ZmieńRozmiarObrazu(BufferedImage img, int newW, int newH) { 
            Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
            BufferedImage dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_3BYTE_BGR);
            Graphics2D g2d = dimg.createGraphics();
            g2d.drawImage(tmp, 0, 0, null);
            g2d.dispose();

    return dimg;
}
    
    
    
    public void Odswierzenie(){
                                      this.repaint();
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoListyGalaktyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNastępny;
    private javax.swing.JButton ButtonPoprzedni;
    private javax.swing.JLabel LabelLiczbaJasnychPunktow;
    private javax.swing.JLabel LabelLiczbaJasnychPunktowWartość;
    private javax.swing.JLabel LabelLiczbaWykrytychJąderGalaktyki;
    private javax.swing.JLabel LabelLiczbaWykrytychJąderGalaktykiWartość;
    private javax.swing.JLabel LabelPikseleBiałe;
    private javax.swing.JLabel LabelPikseleBiałeWartość;
    private javax.swing.JLabel LabelPikseleJasne;
    private javax.swing.JLabel LabelPikseleJasneWartość;
    private javax.swing.JLabel LabelPrzeglądanaGalaktyka;
    private javax.swing.JLabel LabelTypGalaktyki;
    private javax.swing.JLabel LabelTypGalaktykiWartość;
    private javax.swing.JLabel LabelWidok;
    private javax.swing.JLabel LabelWidokWartość;
    private javax.swing.JLabel LabelŹródło;
    private javax.swing.JLabel LabelŹródłoWartość;
    private javax.swing.JPanel PanelMiniatura;
    private javax.swing.JPanel PanelWyświetlacz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
