/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selektorgalaktyk;

/**
 *
 * @author Norbert
 */
public class PanelSterowania extends javax.swing.JFrame {

    /**
     * Creates new form PanelSterowania
     */
    public PanelSterowania() {
        super("Selektor Galaktyczny");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Konsola = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUstawieniaObrazu = new javax.swing.JMenu();
        NatezenieKolorow = new javax.swing.JMenuItem();
        UstawieniaObrazu = new javax.swing.JMenuItem();
        OperacjeNaObrazach = new javax.swing.JMenuItem();
        MenuUstawieniaSelekcji = new javax.swing.JMenu();
        ParametryDetekcji = new javax.swing.JMenuItem();
        UstawieniaPłaskiPrzekątny = new javax.swing.JMenuItem();
        UstawieniaPłaskiSymetryczny = new javax.swing.JMenuItem();
        UstawieniaPełny = new javax.swing.JMenuItem();
        UstawieniaNieregularne = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Konsola.setColumns(20);
        Konsola.setRows(5);
        jScrollPane1.setViewportView(Konsola);

        jButton1.setText("Wybierz folder żródłowy");

        jButton2.setText("Wybierz folder wyjściowy");

        jButton3.setText("Zapisz Wynikowe Obrazy");

        jButton4.setText("Załaduj pojedyńczy Obraz");

        jButton5.setText("Okno edycji dla jednego obrazu");

        jButton6.setText("Załadowanie Oryginału");

        jButton7.setText("Wykonanie Selekcji Masowej");

        jButton8.setText("Wykonanie Selekcji Pojedyńczej");

        jButton9.setText("Lista Galaktyk ");

        jLabel1.setText("Konsola komunikatów");

        MenuUstawieniaObrazu.setText("Ustawienia Obrazu");

        NatezenieKolorow.setText("Natężenie Kolorów");
        MenuUstawieniaObrazu.add(NatezenieKolorow);

        UstawieniaObrazu.setText("Ustawienia Obrazu");
        MenuUstawieniaObrazu.add(UstawieniaObrazu);

        OperacjeNaObrazach.setText("Operacje Na Obrazach");
        MenuUstawieniaObrazu.add(OperacjeNaObrazach);

        jMenuBar1.add(MenuUstawieniaObrazu);

        MenuUstawieniaSelekcji.setText("Ustawienia Selekcji");

        ParametryDetekcji.setText("Parametry Detekcji");
        MenuUstawieniaSelekcji.add(ParametryDetekcji);

        UstawieniaPłaskiPrzekątny.setText("Ustawienia Płaski - Przekątny ");
        UstawieniaPłaskiPrzekątny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawieniaPłaskiPrzekątnyActionPerformed(evt);
            }
        });
        MenuUstawieniaSelekcji.add(UstawieniaPłaskiPrzekątny);

        UstawieniaPłaskiSymetryczny.setText("Ustawienia Płaski - Symetryczny");
        UstawieniaPłaskiSymetryczny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawieniaPłaskiSymetrycznyActionPerformed(evt);
            }
        });
        MenuUstawieniaSelekcji.add(UstawieniaPłaskiSymetryczny);

        UstawieniaPełny.setText("Ustawienia Pełny");
        MenuUstawieniaSelekcji.add(UstawieniaPełny);

        UstawieniaNieregularne.setText("Ustawienia Nieregularne");
        MenuUstawieniaSelekcji.add(UstawieniaNieregularne);

        jMenuBar1.add(MenuUstawieniaSelekcji);

        Pomoc.setText("Pomoc");
        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addGap(0, 224, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UstawieniaPłaskiPrzekątnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawieniaPłaskiPrzekątnyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UstawieniaPłaskiPrzekątnyActionPerformed

    private void UstawieniaPłaskiSymetrycznyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawieniaPłaskiSymetrycznyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UstawieniaPłaskiSymetrycznyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSterowania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PanelSterowania().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Konsola;
    private javax.swing.JMenu MenuUstawieniaObrazu;
    private javax.swing.JMenu MenuUstawieniaSelekcji;
    private javax.swing.JMenuItem NatezenieKolorow;
    private javax.swing.JMenuItem OperacjeNaObrazach;
    private javax.swing.JMenuItem ParametryDetekcji;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JMenuItem UstawieniaNieregularne;
    private javax.swing.JMenuItem UstawieniaObrazu;
    private javax.swing.JMenuItem UstawieniaPełny;
    private javax.swing.JMenuItem UstawieniaPłaskiPrzekątny;
    private javax.swing.JMenuItem UstawieniaPłaskiSymetryczny;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
