/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selektorgalaktyk;

/**
 *
 * @author Norbert
 */
public class PanelSterowania extends javax.swing.JFrame {

    /**
     * Creates new form PanelSterowania
     */
    public PanelSterowania() {
        super("Selektor Galaktyczny");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Konsola = new javax.swing.JTextArea();
        WybierzFolderZrodlowy = new javax.swing.JButton();
        WybierzFolderWyjsciowy = new javax.swing.JButton();
        ZapiszWynikoweObrazy = new javax.swing.JButton();
        ZaladujPojedynczyObraz = new javax.swing.JButton();
        OknoEdycjiDlaPojedynczegoObrazu = new javax.swing.JButton();
        ZaladowanieOryginalu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        WykonanieSelekcjiMasowej = new javax.swing.JButton();
        WykonanieSelekcjiPojedynczej = new javax.swing.JButton();
        ListaGalaktyk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelGlowny = new javax.swing.JLayeredPane();
        NatezenieKolorowZakladka = new javax.swing.JPanel();
        SliderCzerwony = new javax.swing.JSlider();
        LabelCzerwony = new javax.swing.JLabel();
        LabelZielony = new javax.swing.JLabel();
        SliderZielony = new javax.swing.JSlider();
        LabelNiebieski = new javax.swing.JLabel();
        SliderNiebieski = new javax.swing.JSlider();
        NatezenieCzerwony = new javax.swing.JTextField();
        NatezenieZielony = new javax.swing.JTextField();
        NatezenieNiebieski = new javax.swing.JTextField();
        UstawieniaObrazuZakladka = new javax.swing.JPanel();
        SliderJasnosc = new javax.swing.JSlider();
        LabelJasnosc = new javax.swing.JLabel();
        LabelKontrast = new javax.swing.JLabel();
        SliderKontrast = new javax.swing.JSlider();
        LabelWartoscProgowa = new javax.swing.JLabel();
        SliderWartoscProgowa = new javax.swing.JSlider();
        ToggleProgowanie = new javax.swing.JToggleButton();
        ToggleEfektPrzyciemniania = new javax.swing.JToggleButton();
        ToggleEfektRozjasniania = new javax.swing.JToggleButton();
        WartoscJasnosc = new javax.swing.JTextField();
        WartoscKontrast = new javax.swing.JTextField();
        WartoscProgowa = new javax.swing.JTextField();
        OperacjeNaObrazachZakladka = new javax.swing.JPanel();
        WielkoscObrazuX = new javax.swing.JSlider();
        LabelWielkoscObrazuZapisanegoPoziom = new javax.swing.JLabel();
        LabelWielkoscObrazuPion = new javax.swing.JLabel();
        WielkoscObrazuY = new javax.swing.JSlider();
        ButtonStworzPlikJPGzTeraźniejszymUstawieniem = new javax.swing.JButton();
        ButtonStworzPlikPDFzTerazniejszymUstawieniem = new javax.swing.JButton();
        WartoscObrazuZapisanegoPoziom = new javax.swing.JTextField();
        WartoscObrazuZapisanegoPion = new javax.swing.JTextField();
        ParametryDetekcjiZakladka = new javax.swing.JPanel();
        SliderRozmycie = new javax.swing.JSlider();
        LabelRozmycie = new javax.swing.JLabel();
        LabelCzulosc = new javax.swing.JLabel();
        SliderCzulosc = new javax.swing.JSlider();
        LabelMinWielkoscX = new javax.swing.JLabel();
        SliderMinWielkoscX = new javax.swing.JSlider();
        LabelMinWielkoscY = new javax.swing.JLabel();
        SliderMinWielkoscY = new javax.swing.JSlider();
        WartoscRozmycie = new javax.swing.JTextField();
        WartoscCzulosc = new javax.swing.JTextField();
        WartoscMinimalnaX = new javax.swing.JTextField();
        WartoscMinimalnaY = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUstawieniaObrazu = new javax.swing.JMenu();
        NatezenieKolorow = new javax.swing.JMenuItem();
        UstawieniaObrazu = new javax.swing.JMenuItem();
        OperacjeNaObrazach = new javax.swing.JMenuItem();
        MenuUstawieniaSelekcji = new javax.swing.JMenu();
        ParametryDetekcji = new javax.swing.JMenuItem();
        UstawieniaPłaskiPrzekątny = new javax.swing.JMenuItem();
        UstawieniaPłaskiSymetryczny = new javax.swing.JMenuItem();
        UstawieniaPełny = new javax.swing.JMenuItem();
        UstawieniaNieregularne = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Konsola.setColumns(20);
        Konsola.setRows(5);
        jScrollPane1.setViewportView(Konsola);

        WybierzFolderZrodlowy.setText("Wybierz folder żródłowy");

        WybierzFolderWyjsciowy.setText("Wybierz folder wyjściowy");

        ZapiszWynikoweObrazy.setText("Zapisz Wynikowe Obrazy");

        ZaladujPojedynczyObraz.setText("Załaduj pojedyńczy Obraz");

        OknoEdycjiDlaPojedynczegoObrazu.setText("Okno edycji dla jednego obrazu");

        ZaladowanieOryginalu.setText("Załadowanie Oryginału");

        WykonanieSelekcjiMasowej.setText("Wykonanie Selekcji Masowej");

        WykonanieSelekcjiPojedynczej.setText("Wykonanie Selekcji Pojedyńczej");

        ListaGalaktyk.setText("Lista Galaktyk ");

        jLabel1.setText("Konsola komunikatów");

        LabelCzerwony.setText("Czerwony");

        LabelZielony.setText("Zielony");

        LabelNiebieski.setText("Niebieski");

        javax.swing.GroupLayout NatezenieKolorowZakladkaLayout = new javax.swing.GroupLayout(NatezenieKolorowZakladka);
        NatezenieKolorowZakladka.setLayout(NatezenieKolorowZakladkaLayout);
        NatezenieKolorowZakladkaLayout.setHorizontalGroup(
            NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NatezenieKolorowZakladkaLayout.createSequentialGroup()
                .addGroup(NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SliderCzerwony, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(LabelCzerwony)
                    .addComponent(LabelZielony)
                    .addComponent(SliderZielony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelNiebieski)
                    .addComponent(SliderNiebieski, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NatezenieZielony)
                    .addComponent(NatezenieNiebieski, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(NatezenieCzerwony, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 167, Short.MAX_VALUE))
        );
        NatezenieKolorowZakladkaLayout.setVerticalGroup(
            NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NatezenieKolorowZakladkaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LabelCzerwony)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NatezenieCzerwony)
                    .addComponent(SliderCzerwony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelZielony)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NatezenieZielony)
                    .addComponent(SliderZielony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNiebieski)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NatezenieKolorowZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NatezenieNiebieski)
                    .addComponent(SliderNiebieski, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        LabelJasnosc.setText("Jasność");

        LabelKontrast.setText("Konstrast");

        LabelWartoscProgowa.setText("Wartosc Progowa");

        ToggleProgowanie.setText("Progowanie");

        ToggleEfektPrzyciemniania.setText("Efekt Przyciemniania");

        ToggleEfektRozjasniania.setText("Efekt Rozjaśniania");

        javax.swing.GroupLayout UstawieniaObrazuZakladkaLayout = new javax.swing.GroupLayout(UstawieniaObrazuZakladka);
        UstawieniaObrazuZakladka.setLayout(UstawieniaObrazuZakladkaLayout);
        UstawieniaObrazuZakladkaLayout.setHorizontalGroup(
            UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                        .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJasnosc)
                            .addComponent(LabelKontrast)
                            .addComponent(LabelWartoscProgowa))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                        .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                                .addComponent(SliderWartoscProgowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WartoscProgowa))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                                .addComponent(SliderKontrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WartoscKontrast))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                                .addComponent(SliderJasnosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WartoscJasnosc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToggleEfektPrzyciemniania, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(ToggleEfektRozjasniania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToggleProgowanie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UstawieniaObrazuZakladkaLayout.setVerticalGroup(
            UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstawieniaObrazuZakladkaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJasnosc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderJasnosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ToggleEfektPrzyciemniania)
                        .addComponent(WartoscJasnosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelKontrast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderKontrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ToggleEfektRozjasniania)
                        .addComponent(WartoscKontrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelWartoscProgowa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UstawieniaObrazuZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderWartoscProgowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WartoscProgowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToggleProgowanie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelWielkoscObrazuZapisanegoPoziom.setText("Wielkość obrazu zapisanego poziom w %");

        LabelWielkoscObrazuPion.setText("Wielkość obrazu zapisanego pion w %");

        ButtonStworzPlikJPGzTeraźniejszymUstawieniem.setText("Stwórz Plik JPG z Teraźniejszym ustawieniem");

        ButtonStworzPlikPDFzTerazniejszymUstawieniem.setText("Stwórz Plik PDF z Teraźniejszym Ustawieniem");

        javax.swing.GroupLayout OperacjeNaObrazachZakladkaLayout = new javax.swing.GroupLayout(OperacjeNaObrazachZakladka);
        OperacjeNaObrazachZakladka.setLayout(OperacjeNaObrazachZakladkaLayout);
        OperacjeNaObrazachZakladkaLayout.setHorizontalGroup(
            OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacjeNaObrazachZakladkaLayout.createSequentialGroup()
                .addGroup(OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelWielkoscObrazuZapisanegoPoziom)
                    .addComponent(LabelWielkoscObrazuPion)
                    .addComponent(ButtonStworzPlikJPGzTeraźniejszymUstawieniem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonStworzPlikPDFzTerazniejszymUstawieniem, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(WielkoscObrazuX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WielkoscObrazuY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WartoscObrazuZapisanegoPoziom)
                    .addComponent(WartoscObrazuZapisanegoPion, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OperacjeNaObrazachZakladkaLayout.setVerticalGroup(
            OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacjeNaObrazachZakladkaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelWielkoscObrazuZapisanegoPoziom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WartoscObrazuZapisanegoPoziom)
                    .addComponent(WielkoscObrazuX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelWielkoscObrazuPion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacjeNaObrazachZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WartoscObrazuZapisanegoPion)
                    .addComponent(WielkoscObrazuY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonStworzPlikJPGzTeraźniejszymUstawieniem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonStworzPlikPDFzTerazniejszymUstawieniem)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        LabelRozmycie.setText("Rozmycie");

        LabelCzulosc.setText("Czułość");

        LabelMinWielkoscX.setText("Minimalna Wielkość X");

        LabelMinWielkoscY.setText("Minimalna Wielkość Y");

        WartoscCzulosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WartoscCzuloscActionPerformed(evt);
            }
        });

        WartoscMinimalnaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WartoscMinimalnaXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ParametryDetekcjiZakladkaLayout = new javax.swing.GroupLayout(ParametryDetekcjiZakladka);
        ParametryDetekcjiZakladka.setLayout(ParametryDetekcjiZakladkaLayout);
        ParametryDetekcjiZakladkaLayout.setHorizontalGroup(
            ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                        .addComponent(SliderRozmycie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WartoscRozmycie))
                    .addComponent(LabelRozmycie)
                    .addComponent(LabelCzulosc)
                    .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                        .addComponent(SliderCzulosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WartoscCzulosc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelMinWielkoscX)
                    .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                        .addComponent(SliderMinWielkoscX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WartoscMinimalnaX, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelMinWielkoscY)
                    .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                        .addComponent(SliderMinWielkoscY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WartoscMinimalnaY, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        ParametryDetekcjiZakladkaLayout.setVerticalGroup(
            ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParametryDetekcjiZakladkaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRozmycie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderRozmycie, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WartoscRozmycie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCzulosc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderCzulosc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WartoscCzulosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelMinWielkoscX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderMinWielkoscX, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WartoscMinimalnaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelMinWielkoscY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParametryDetekcjiZakladkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderMinWielkoscY, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WartoscMinimalnaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGlowny.setLayer(NatezenieKolorowZakladka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelGlowny.setLayer(UstawieniaObrazuZakladka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelGlowny.setLayer(OperacjeNaObrazachZakladka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelGlowny.setLayer(ParametryDetekcjiZakladka, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelGlownyLayout = new javax.swing.GroupLayout(PanelGlowny);
        PanelGlowny.setLayout(PanelGlownyLayout);
        PanelGlownyLayout.setHorizontalGroup(
            PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OperacjeNaObrazachZakladka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelGlownyLayout.createSequentialGroup()
                    .addComponent(NatezenieKolorowZakladka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UstawieniaObrazuZakladka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ParametryDetekcjiZakladka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGlownyLayout.setVerticalGroup(
            PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OperacjeNaObrazachZakladka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NatezenieKolorowZakladka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UstawieniaObrazuZakladka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGlownyLayout.createSequentialGroup()
                    .addComponent(ParametryDetekcjiZakladka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        MenuUstawieniaObrazu.setText("Ustawienia Obrazu");

        NatezenieKolorow.setText("Natężenie Kolorów");
        NatezenieKolorow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NatezenieKolorowMouseClicked(evt);
            }
        });
        NatezenieKolorow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NatezenieKolorowActionPerformed(evt);
            }
        });
        MenuUstawieniaObrazu.add(NatezenieKolorow);

        UstawieniaObrazu.setText("Ustawienia Obrazu");
        UstawieniaObrazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawieniaObrazuActionPerformed(evt);
            }
        });
        MenuUstawieniaObrazu.add(UstawieniaObrazu);

        OperacjeNaObrazach.setText("Operacje Na Obrazach");
        OperacjeNaObrazach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacjeNaObrazachActionPerformed(evt);
            }
        });
        MenuUstawieniaObrazu.add(OperacjeNaObrazach);

        jMenuBar1.add(MenuUstawieniaObrazu);

        MenuUstawieniaSelekcji.setText("Ustawienia Selekcji");

        ParametryDetekcji.setText("Parametry Detekcji");
        ParametryDetekcji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParametryDetekcjiActionPerformed(evt);
            }
        });
        MenuUstawieniaSelekcji.add(ParametryDetekcji);

        UstawieniaPłaskiPrzekątny.setText("Ustawienia Płaski - Przekątny ");
        UstawieniaPłaskiPrzekątny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawieniaPłaskiPrzekątnyActionPerformed(evt);
            }
        });
        MenuUstawieniaSelekcji.add(UstawieniaPłaskiPrzekątny);

        UstawieniaPłaskiSymetryczny.setText("Ustawienia Płaski - Symetryczny");
        UstawieniaPłaskiSymetryczny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawieniaPłaskiSymetrycznyActionPerformed(evt);
            }
        });
        MenuUstawieniaSelekcji.add(UstawieniaPłaskiSymetryczny);

        UstawieniaPełny.setText("Ustawienia Pełny");
        MenuUstawieniaSelekcji.add(UstawieniaPełny);

        UstawieniaNieregularne.setText("Ustawienia Nieregularne");
        MenuUstawieniaSelekcji.add(UstawieniaNieregularne);

        jMenuBar1.add(MenuUstawieniaSelekcji);

        Pomoc.setText("Pomoc");
        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ZaladujPojedynczyObraz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OknoEdycjiDlaPojedynczegoObrazu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZaladowanieOryginalu, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(WybierzFolderZrodlowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WybierzFolderWyjsciowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZapiszWynikoweObrazy, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WykonanieSelekcjiMasowej)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WykonanieSelekcjiPojedynczej)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaGalaktyk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addComponent(PanelGlowny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(WybierzFolderWyjsciowy)
                        .addComponent(ZapiszWynikoweObrazy)
                        .addComponent(WybierzFolderZrodlowy))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZaladujPojedynczyObraz)
                            .addComponent(OknoEdycjiDlaPojedynczegoObrazu)
                            .addComponent(ZaladowanieOryginalu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WykonanieSelekcjiMasowej)
                            .addComponent(WykonanieSelekcjiPojedynczej)
                            .addComponent(ListaGalaktyk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelGlowny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UstawieniaPłaskiPrzekątnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawieniaPłaskiPrzekątnyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UstawieniaPłaskiPrzekątnyActionPerformed

    private void UstawieniaPłaskiSymetrycznyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawieniaPłaskiSymetrycznyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UstawieniaPłaskiSymetrycznyActionPerformed

    private void NatezenieKolorowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NatezenieKolorowActionPerformed
    NatezenieKolorowZakladka.setVisible(true);
    UstawieniaObrazuZakladka.setVisible(false);
    OperacjeNaObrazachZakladka.setVisible(false);
    ParametryDetekcjiZakladka.setVisible(false);
    
    
    }//GEN-LAST:event_NatezenieKolorowActionPerformed

    private void NatezenieKolorowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NatezenieKolorowMouseClicked
    
    }//GEN-LAST:event_NatezenieKolorowMouseClicked

    private void UstawieniaObrazuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawieniaObrazuActionPerformed
    NatezenieKolorowZakladka.setVisible(false);
    UstawieniaObrazuZakladka.setVisible(true);
    OperacjeNaObrazachZakladka.setVisible(false);  
    ParametryDetekcjiZakladka.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_UstawieniaObrazuActionPerformed

    private void OperacjeNaObrazachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacjeNaObrazachActionPerformed
    NatezenieKolorowZakladka.setVisible(false);
    UstawieniaObrazuZakladka.setVisible(false); 
    OperacjeNaObrazachZakladka.setVisible(true);
    ParametryDetekcjiZakladka.setVisible(false);
    }//GEN-LAST:event_OperacjeNaObrazachActionPerformed

    private void WartoscCzuloscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WartoscCzuloscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WartoscCzuloscActionPerformed

    private void WartoscMinimalnaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WartoscMinimalnaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WartoscMinimalnaXActionPerformed

    private void ParametryDetekcjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParametryDetekcjiActionPerformed
     NatezenieKolorowZakladka.setVisible(false);
    UstawieniaObrazuZakladka.setVisible(false); 
    OperacjeNaObrazachZakladka.setVisible(false);
    ParametryDetekcjiZakladka.setVisible(true);
    }//GEN-LAST:event_ParametryDetekcjiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSterowania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PanelSterowania().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonStworzPlikJPGzTeraźniejszymUstawieniem;
    private javax.swing.JButton ButtonStworzPlikPDFzTerazniejszymUstawieniem;
    private javax.swing.JTextArea Konsola;
    private javax.swing.JLabel LabelCzerwony;
    private javax.swing.JLabel LabelCzulosc;
    private javax.swing.JLabel LabelJasnosc;
    private javax.swing.JLabel LabelKontrast;
    private javax.swing.JLabel LabelMinWielkoscX;
    private javax.swing.JLabel LabelMinWielkoscY;
    private javax.swing.JLabel LabelNiebieski;
    private javax.swing.JLabel LabelRozmycie;
    private javax.swing.JLabel LabelWartoscProgowa;
    private javax.swing.JLabel LabelWielkoscObrazuPion;
    private javax.swing.JLabel LabelWielkoscObrazuZapisanegoPoziom;
    private javax.swing.JLabel LabelZielony;
    private javax.swing.JButton ListaGalaktyk;
    private javax.swing.JMenu MenuUstawieniaObrazu;
    private javax.swing.JMenu MenuUstawieniaSelekcji;
    private javax.swing.JTextField NatezenieCzerwony;
    private javax.swing.JMenuItem NatezenieKolorow;
    private javax.swing.JPanel NatezenieKolorowZakladka;
    private javax.swing.JTextField NatezenieNiebieski;
    private javax.swing.JTextField NatezenieZielony;
    private javax.swing.JButton OknoEdycjiDlaPojedynczegoObrazu;
    private javax.swing.JMenuItem OperacjeNaObrazach;
    private javax.swing.JPanel OperacjeNaObrazachZakladka;
    private javax.swing.JLayeredPane PanelGlowny;
    private javax.swing.JMenuItem ParametryDetekcji;
    private javax.swing.JPanel ParametryDetekcjiZakladka;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JSlider SliderCzerwony;
    private javax.swing.JSlider SliderCzulosc;
    private javax.swing.JSlider SliderJasnosc;
    private javax.swing.JSlider SliderKontrast;
    private javax.swing.JSlider SliderMinWielkoscX;
    private javax.swing.JSlider SliderMinWielkoscY;
    private javax.swing.JSlider SliderNiebieski;
    private javax.swing.JSlider SliderRozmycie;
    private javax.swing.JSlider SliderWartoscProgowa;
    private javax.swing.JSlider SliderZielony;
    private javax.swing.JToggleButton ToggleEfektPrzyciemniania;
    private javax.swing.JToggleButton ToggleEfektRozjasniania;
    private javax.swing.JToggleButton ToggleProgowanie;
    private javax.swing.JMenuItem UstawieniaNieregularne;
    private javax.swing.JMenuItem UstawieniaObrazu;
    private javax.swing.JPanel UstawieniaObrazuZakladka;
    private javax.swing.JMenuItem UstawieniaPełny;
    private javax.swing.JMenuItem UstawieniaPłaskiPrzekątny;
    private javax.swing.JMenuItem UstawieniaPłaskiSymetryczny;
    private javax.swing.JTextField WartoscCzulosc;
    private javax.swing.JTextField WartoscJasnosc;
    private javax.swing.JTextField WartoscKontrast;
    private javax.swing.JTextField WartoscMinimalnaX;
    private javax.swing.JTextField WartoscMinimalnaY;
    private javax.swing.JTextField WartoscObrazuZapisanegoPion;
    private javax.swing.JTextField WartoscObrazuZapisanegoPoziom;
    private javax.swing.JTextField WartoscProgowa;
    private javax.swing.JTextField WartoscRozmycie;
    private javax.swing.JSlider WielkoscObrazuX;
    private javax.swing.JSlider WielkoscObrazuY;
    private javax.swing.JButton WybierzFolderWyjsciowy;
    private javax.swing.JButton WybierzFolderZrodlowy;
    private javax.swing.JButton WykonanieSelekcjiMasowej;
    private javax.swing.JButton WykonanieSelekcjiPojedynczej;
    private javax.swing.JButton ZaladowanieOryginalu;
    private javax.swing.JButton ZaladujPojedynczyObraz;
    private javax.swing.JButton ZapiszWynikoweObrazy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
