/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selektorgalaktyk;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Quchi
 */
public class WyborPliku extends javax.swing.JFrame {

    FileNameExtensionFilter f_sel;/**
     * Creates new form WyborPliku
     */
    

     public  WyborPliku() {
         
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WybieraczPliku = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WybieraczPliku.setDialogTitle("Wybór pliku z obrazem Galaktyki");
        WybieraczPliku.addChoosableFileFilter( new FileNameExtensionFilter( "png", "png") );
        WybieraczPliku.addChoosableFileFilter( new FileNameExtensionFilter( "jpeg", "jpg", "jpeg" ) );
        WybieraczPliku.addChoosableFileFilter( new FileNameExtensionFilter( "gif", "gif" ) );
        WybieraczPliku.addChoosableFileFilter( new FileNameExtensionFilter( "tga", "tga" ) );
        WybieraczPliku.addChoosableFileFilter( new FileNameExtensionFilter( "tiff", "tif", "tiff" ) );
        WybieraczPliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WybieraczPlikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WybieraczPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WybieraczPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void WybieraczPlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WybieraczPlikuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WybieraczPlikuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WyborPliku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
          java.awt.EventQueue.invokeLater(() -> {
            new WyborPliku().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser WybieraczPliku;
    // End of variables declaration//GEN-END:variables
}
